version: 2
orbs:
  node: circleci/node@14.2.0
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run:
          name: install
          command: |
            sudo apt -y install lcov
            npm install
      - run:
          name: cpus
          command: nproc
      - run:
          name: coverage
          command: npm run ci-coverage
