version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.2.0-buster
    steps:
      - checkout
      - run:
          name: install
          command: |
            echo 'deb http://deb.debian.org/debian testing main' | sudo tee /etc/apt/sources.list.d/testing.list > /dev/null
            sudo apt update
            sudo apt upgrade
            sudo apt -y install lcov
            npm install
      - run:
          name: cpus
          command: nproc
      - run:
          name: versions
          command: |
            gcc --version
            gcov --version
            lcov --version
      - run:
          name: coverage
          command: npm run ci-coverage
