version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.2.0-buster
    steps:
      - checkout
      - run:
          name: install
          command: |
            sudo apt -y install lcov
            npm install
      - run:
          name: cpus
          command: nproc
      - run:
          name: coverage
          command: npm run ci-coverage
