name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12, 14, 16]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update APT
        run: sudo apt update

      - name: Install dependencies
        run: sudo apt install lcov

      - name: Print number of CPUs
        run: nproc

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm ci

      - name: Lint
        run: npx grunt lint

      - name: Coverage
        run: npm run coverage

      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          files: coverage/lcov_final.info
