name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12, 14, 16]
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update APT
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update

      - name: Install OS dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install lcov

      - name: Print number of CPUs
        if: matrix.os == 'ubuntu-latest'
        run: nproc

      - name: Print number of CPUs
        if: matrix.os == 'macos-latest'
        run: sysctl -n hw.logicalcpu

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Reconfigure git to use HTTPS
        run: git config --global url.https://github.com/.insteadOf ssh://git@github.com/

      - name: Install packages
        run: npm ci

      - name: Lint
        if: matrix.os == 'ubuntu-latest'
        run: npx grunt lint

      - name: Coverage
        if: matrix.os == 'ubuntu-latest'
        run: npm run coverage

      - name: Coveralls
        if: matrix.os == 'ubuntu-latest'
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage/lcov_final.info

      - name: Test
        if: matrix.os == 'macos-latest'
        run: npx grunt test
